# Generated by Django 4.2.7 on 2023-11-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=13, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
