# Generated by Django 4.2.7 on 2023-11-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_venue_email_alter_venue_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ClubUser',
        ),
    ]
